
package Screens;

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

import BookClass.Book;
import BookClass.Genre;
import BookClass.Inventory;
import BookClass.Status;

/**
 *
 * @author belal
 */
public class AddBookScreen extends javax.swing.JFrame {

    /**
     * Creates new form AddBookScreen
     */
    public AddBookScreen(String isbn) {
        initComponents();
        this.isbn = isbn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        AddBookHeader = new javax.swing.JLabel();
        genreLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        availabilityLabel = new javax.swing.JLabel();
        keywordLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        bookTitleTextField = new javax.swing.JTextField();
        genreComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        descTextArea = new javax.swing.JTextArea();
        availabilityComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        keywordTextArea = new javax.swing.JTextArea();
        authorTextField = new javax.swing.JTextField();
        submitBookButton = new javax.swing.JButton();
        imagePathLabel = new javax.swing.JLabel();
        imagePathTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddBookHeader.setFont(new java.awt.Font("Segue UI", Font.BOLD, 18)); // NOI18N
        AddBookHeader.setText("Add Book");

        genreLabel.setFont(new java.awt.Font("Segue UI", Font.PLAIN, 14)); // NOI18N
        genreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genreLabel.setText("Genre");

        titleLabel.setFont(new java.awt.Font("Segue UI", Font.PLAIN, 14)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Title");

        descLabel.setFont(new java.awt.Font("Segue UI", Font.PLAIN, 14)); // NOI18N
        descLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descLabel.setText("Description");

        availabilityLabel.setFont(new java.awt.Font("Segue UI", Font.PLAIN, 14)); // NOI18N
        availabilityLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        availabilityLabel.setText("Availability");

        keywordLabel.setFont(new java.awt.Font("Segue UI", Font.PLAIN, 14)); // NOI18N
        keywordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keywordLabel.setText("Keywords");

        authorLabel.setFont(new java.awt.Font("Segue UI", Font.PLAIN, 14)); // NOI18N
        authorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorLabel.setText("Authors");

        genreComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE","HISTORY", "PHILOSOPHY"
                , "SCIENCE", "FICTION","MYSTERY","ROMANCE","HORROR","FANTASY","COOKING","ART","MUSIC","SPORTS","OTHER"}));

        descTextArea.setColumns(20);
        descTextArea.setRows(5);
        jScrollPane1.setViewportView(descTextArea);

        availabilityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AVAILABLE", "UNAVAILABLE", "BORROWED", "LATE", "LOST", "DAMAGED" }));

        keywordTextArea.setColumns(20);
        keywordTextArea.setRows(5);
        jScrollPane2.setViewportView(keywordTextArea);

        submitBookButton.setFont(new java.awt.Font("Segue UI", Font.BOLD, 14)); // NOI18N
        submitBookButton.setText("Submit");
        submitBookButton.addActionListener(this::submitBookButtonActionPerformed);

        imagePathLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagePathLabel.setText("Image Path");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(230, 230, 230)
                                                .addComponent(AddBookHeader))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(descLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                                        .addComponent(genreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(imagePathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(genreComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 132, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                        .addComponent(bookTitleTextField)
                                                        .addComponent(imagePathTextField))
                                                .addGap(40, 40, 40)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(authorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(keywordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(availabilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(availabilityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(210, 210, 210)
                                                .addComponent(submitBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(AddBookHeader)
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(bookTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(genreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(genreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(descLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(authorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(9, 9, 9)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(availabilityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(availabilityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(keywordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(imagePathLabel)
                                        .addComponent(imagePathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(submitBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>

    private void submitBookButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int flag = 0;
        StringBuffer info = new StringBuffer();
        Book book = new Book();

        if (bookTitleTextField.getText().isBlank()) {
            flag++;
            info.append("Title ");
        }else {

        }

        if (authorTextField.getText().isBlank()) {
            flag++;
            info.append("Author ");
        }

        if (descTextArea.getText().isBlank()) {
            flag++;
            info.append("Description ");
        }


        if (flag >= 1) {
            JOptionPane.showMessageDialog(null, "Incomplete info: " + info, "Fatal Error" , JOptionPane.ERROR_MESSAGE);
        }else{
            book.setISBN(isbn);
            book.setTitle(bookTitleTextField.getText());
            book.setAuthor(authorTextField.getText());
            book.setDescription(descTextArea.getText());
            book.setImagePath((imagePathTextField.getText()));

            Genre genre = null;

            try {
                for (Genre g : Genre.values()) {
                    if (g.toString().equals(Objects.requireNonNull(genreComboBox.getSelectedItem()).toString()))
                        genre = g;
                }
                book.setGenreType(genre);
            }catch(NullPointerException npe){
                JOptionPane.showMessageDialog(null, "Something went wrong when selecting a genre", "Error", JOptionPane.ERROR_MESSAGE);
            }

            Status status = null;

            try{
                for(Status s: Status.values())
                    if(s.toString().equals(availabilityComboBox.getSelectedItem().toString()))
                        status = s;
                book.setAvailability(status);
            }catch(NullPointerException npe){
                JOptionPane.showMessageDialog(null, "Something went wrong when selecting an availability status", "Error", JOptionPane.ERROR_MESSAGE);
            }
            Inventory.getBooks().add(book);

            JOptionPane.showMessageDialog(null, "Book added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);

            LibrarianScreen librarianScreen = new LibrarianScreen();
            librarianScreen.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String []args) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBookScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBookScreen("1234").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private final String isbn;
    private javax.swing.JLabel AddBookHeader;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JComboBox<String> availabilityComboBox;
    private javax.swing.JLabel availabilityLabel;
    private javax.swing.JTextField bookTitleTextField;
    private javax.swing.JLabel descLabel;
    private javax.swing.JTextArea descTextArea;
    private javax.swing.JComboBox<String> genreComboBox;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JLabel imagePathLabel;
    private javax.swing.JTextField imagePathTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel keywordLabel;
    private javax.swing.JTextArea keywordTextArea;
    private javax.swing.JButton submitBookButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration
}
