
package Screens;
import BookClass.*;
import UserClass.*;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
/**
 *
 * @author belal
 */
public class CartScreen extends javax.swing.JFrame {

    /**
     * Creates new form CartScreen
     */
    public CartScreen() {
        initComponents();
        initializeBorrowedBooks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initializeBorrowedBooks() {
        // For testing, I'm adding some dummy books
        borrowedBooks.add(new Book("Book 1", "John Doe", Genre.FICTION, "./assets/default.png"));
        borrowedBooks.add(new Book("Book 2", "Jane Smith", Genre.HORROR, "./assets/default.png"));
        borrowedBooks.add(new Book("Book 3", "Alice Johnson", Genre.MYSTERY, "./assets/default.png"));
        borrowedBooks.add(new Book("Book 4", "Bob Brown", Genre.ROMANCE, "./assets/default.png"));
        borrowedBooks.add(new Book("Book 5", "Charlie White", Genre.ART, "./assets/default.png"));
        borrowedBookPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 10, 10));

        for (Book book : borrowedBooks) {

            // Assuming you have image icons stored in book object
            ImageIcon imageIcon = new ImageIcon(book.getImagePath()); // Replace this with actual path
            BookPanel panel = new BookPanel(book.getTitle(), book.getAuthor(), book.getGenreType().toString(), imageIcon);
            panel.setBorder(BorderFactory.createLineBorder(Color.BLACK)); // Optional: Add borders to each book panel
            panel.setBorder(new EmptyBorder(0, 10, 10, 10)); // Top, left, bottom, right padding of 10 pixels
            JButton cancelButton = new JButton("Cancel");

            // Add action listener to the cancel button
            cancelButton.addActionListener(e -> {
                // Handle cancel action here
                // For example, remove the book panel from the borrowedBookPanel
                borrowedBookPanel.remove(panel);
                // Repaint the panel to reflect changes
                borrowedBookPanel.revalidate();
                borrowedBookPanel.repaint();
            });

            JPanel bookContainerPanel = new JPanel(new BorderLayout());
            bookContainerPanel.add(panel, BorderLayout.CENTER);
            bookContainerPanel.add(cancelButton, BorderLayout.SOUTH);

            borrowedBookPanel.add(bookContainerPanel);
            panel.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    // Add your code here to handle click event
                }
            });
        }
    }

    private void initComponents() {

        logoButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        borrowedLabel = new javax.swing.JLabel();
        wishlistLabel = new javax.swing.JLabel();
        borrowedBookPanel = new javax.swing.JPanel();
        wishlistBookPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoButton.setText("logo");

        logoutButton.setText("Logout");

        profileButton.setText("Profile");

        borrowedLabel.setText("Borrowed Books");

        wishlistLabel.setText("Books added to cart");

        borrowedBookPanel.setLayout(new java.awt.GridLayout(1, 5));

        wishlistBookPanel.setLayout(new java.awt.GridLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(logoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(profileButton)
                                .addGap(18, 18, 18)
                                .addComponent(logoutButton)
                                .addGap(15, 15, 15))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(borrowedBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(wishlistBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(borrowedLabel)
                                        .addComponent(wishlistLabel))
                                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(logoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(profileButton)
                                        .addComponent(logoutButton))
                                .addGap(18, 18, 18)
                                .addComponent(borrowedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(borrowedBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(wishlistLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(wishlistBookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private Customer customer;

    private ArrayList<Book> borrowedBooks = new ArrayList<>();
    private javax.swing.JPanel borrowedBookPanel;
    private javax.swing.JLabel borrowedLabel;
    private javax.swing.JButton logoButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton profileButton;
    private javax.swing.JPanel wishlistBookPanel;
    private javax.swing.JLabel wishlistLabel;
    // End of variables declaration
}
