
package Screens;

import BookClass.Book;
import BookClass.Inventory;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author belal
 */
public class GenerateReportScreen extends javax.swing.JFrame {

    /**
     * Creates new form GenerateReportScreen
     */
    public GenerateReportScreen(Book book) {
        initComponents(); this.book = book;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        // Variables declaration - do not modify
        JLabel reportHeaderLabel = new JLabel();
        JLabel bookImageLabel = new JLabel();
        JTextField bookISBNTextField = new JTextField();
        JLabel bookTitleLabel = new JLabel();
        JTextField bookTitleTextField = new JTextField();
        JLabel bookAuthorLabel = new JLabel();
        JTextField bookAuthorTextField = new JTextField();
        JLabel bookGenreLabel = new JLabel();
        JTextField bookGenreTextField = new JTextField();
        JLabel isbnLabel = new JLabel();
        JLabel bookFareLabel = new JLabel();
        JTextField totalBookFareTextField = new JTextField();
        JLabel totalBookingLabel = new JLabel();
        JTextField totalBookingTextField = new JTextField();
        JLabel totalFareLabel = new JLabel();
        JTextField totalFareTextField = new JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        reportHeaderLabel.setFont(new java.awt.Font("Segue UI", Font.BOLD, 18)); // NOI18N
        reportHeaderLabel.setText("Book Report");

        bookImageLabel.setText("book image alt");
        bookImageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bookTitleLabel.setText("Title :");

        bookAuthorLabel.setText("Author :");

        bookGenreLabel.setText("Genre :");

        isbnLabel.setText("ISBN :");

        bookFareLabel.setText("Total fare for this book :");

        totalBookFareTextField.addActionListener(this::totalBookFareTextFieldActionPerformed);

        totalBookingLabel.setFont(new java.awt.Font("Segue UI", Font.BOLD, 14)); // NOI18N
        totalBookingLabel.setText("The  total number of bookings in the system");

        totalBookingTextField.addActionListener(this::totalBookFareTextField1ActionPerformed);

        totalFareLabel.setFont(new java.awt.Font("Segue UI", Font.BOLD, 14)); // NOI18N
        totalFareLabel.setText("The total fare collected from bookings in the system");


        bookISBNTextField.setText(book.getISBN());
        bookISBNTextField.setEditable(false);

        bookTitleTextField.setText(book.getTitle());
        bookTitleTextField.setEditable(false);

        bookAuthorTextField.setText(book.getAuthor());
        bookAuthorTextField.setEditable(false);

        bookGenreTextField.setText(String.valueOf(book.getGenreType()));
        bookGenreTextField.setEditable(false);

        totalBookFareTextField.setText(String.valueOf(book.getTotalFare()));
        totalBookFareTextField.setEditable(false);

        totalBookingTextField.setText(String.valueOf(Inventory.getBorrowedBooks().size()));
        Double totalFare = 0.0;
        for(Book b : Inventory.getBooks()){
            if(b.getTotalFare() != null)
                totalFare += b.getTotalFare();
        }
        totalFareTextField.setText(String.valueOf(totalFare));

        totalFareTextField.addActionListener(this::totalFareTextFieldActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(bookImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(67, 67, 67)
                                                                .addComponent(reportHeaderLabel))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(isbnLabel)
                                                                        .addComponent(bookTitleLabel)
                                                                        .addComponent(bookAuthorLabel)
                                                                        .addComponent(bookGenreLabel)
                                                                        .addComponent(bookFareLabel))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(bookISBNTextField)
                                                                        .addComponent(bookTitleTextField)
                                                                        .addComponent(bookAuthorTextField)
                                                                        .addComponent(bookGenreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                                                        .addComponent(totalBookFareTextField)))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(totalBookingLabel)
                                                        .addComponent(totalFareLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(totalFareTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(totalBookingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(reportHeaderLabel)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bookImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(bookISBNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(bookTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(bookTitleLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(bookAuthorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(bookAuthorLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(bookGenreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(bookGenreLabel)))
                                        .addComponent(isbnLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bookFareLabel)
                                        .addComponent(totalBookFareTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(totalBookingLabel)
                                        .addComponent(totalBookingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(totalFareLabel)
                                        .addComponent(totalFareTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void totalBookFareTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void totalBookFareTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void totalFareTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateReportScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GenerateReportScreen(new Book()).setVisible(true));
    }
    Book book;
    JLabel reportHeaderLabel = new JLabel();
    JLabel bookImageLabel = new JLabel();
    JTextField bookISBNTextField = new JTextField();
    JLabel bookTitleLabel = new JLabel();
    JTextField bookTitleTextField = new JTextField();
    JLabel bookAuthorLabel = new JLabel();
    JTextField bookAuthorTextField = new JTextField();
    JLabel bookGenreLabel = new JLabel();
    JTextField bookGenreTextField = new JTextField();
    JLabel isbnLabel = new JLabel();
    JLabel bookFareLabel = new JLabel();
    JTextField totalBookFareTextField = new JTextField();
    JLabel totalBookingLabel = new JLabel();
    JTextField totalBookingTextField = new JTextField();
    JLabel totalFareLabel = new JLabel();
    JTextField totalFareTextField = new JTextField();
    // End of variables declaration
}
