/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screens;

import BookClass.Book;
import BookClass.Inventory;
import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author belal
 */
public class LibrarianScreen extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianScreen
     */
    public LibrarianScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        books = Inventory.getBooks();
        logoButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        librarianLabel = new javax.swing.JLabel();
        librarianPanel = new javax.swing.JPanel();
        addBookLabel = new javax.swing.JLabel();
        generateReportLabel = new javax.swing.JLabel();
        removeBookLabel = new javax.swing.JLabel();
        updateBookLabel = new javax.swing.JLabel();
        updateBookTextField = new javax.swing.JTextField();
        addBookTextField = new javax.swing.JTextField();
        removeBookTextField = new javax.swing.JTextField();
        generateReportButton = new javax.swing.JButton();
        addBookButton = new javax.swing.JButton();
        removeBookButton = new javax.swing.JButton();
        updateBookButton = new javax.swing.JButton();
        generateReportTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoButton.setText("logo");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        librarianPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        addBookLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addBookLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBookLabel.setText("Add Book");

        generateReportLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        generateReportLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generateReportLabel.setText("Generate Report");

        removeBookLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        removeBookLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removeBookLabel.setText("Remove Book");

        updateBookLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateBookLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateBookLabel.setText("Update Book");

        generateReportButton.setText("Generate");
        generateReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportButtonActionPerformed(evt);
            }
        });

        addBookButton.setText("Confirm");
        addBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookButtonActionPerformed(evt);
            }
        });

        removeBookButton.setText("Confirm");
        removeBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBookButtonActionPerformed(evt);
            }
        });

        updateBookButton.setText("Confirm");
        updateBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBookButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout librarianPanelLayout = new javax.swing.GroupLayout(librarianPanel);
        librarianPanel.setLayout(librarianPanelLayout);
        librarianPanelLayout.setHorizontalGroup(
                librarianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(librarianPanelLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(librarianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(generateReportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(updateBookLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(removeBookLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(librarianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(updateBookTextField)
                                        .addComponent(removeBookTextField)
                                        .addComponent(addBookTextField)
                                        .addComponent(generateReportTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addGroup(librarianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(removeBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(updateBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(generateReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(57, Short.MAX_VALUE))
        );
        librarianPanelLayout.setVerticalGroup(
                librarianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(librarianPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(librarianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addBookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(addBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(librarianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(removeBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(removeBookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(removeBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(librarianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(updateBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(updateBookTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(updateBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(librarianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(generateReportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                        .addComponent(generateReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(generateReportTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(31, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(librarianPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(logoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(49, 49, 49)
                                                .addComponent(librarianLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(50, 50, 50)
                                                .addComponent(logoutButton)))
                                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(logoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(logoutButton)
                                        .addComponent(librarianLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(librarianPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void generateReportButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String isbn = generateReportTextField.getText();
        if(isbn.isBlank()){
            JOptionPane.showMessageDialog(null, "Please enter an ISBN");
            return;
        }
        if(!Book.verifyISBN(isbn)){
            JOptionPane.showMessageDialog(null, "Invalid ISBN");
            return;
        }
        for(Book b : books){
            if(b.getISBN().equals(isbn)){
                GenerateReportScreen generateReportScreen = new GenerateReportScreen(b);
                generateReportScreen.setVisible(true);
                this.setVisible(false);
                this.dispose();
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Book not found");
    }

    private void addBookButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String isbn = addBookTextField.getText();
        System.out.println("isbn: " + isbn);
        if(isbn.isBlank()){
            JOptionPane.showMessageDialog(null, "Please enter an ISBN");
            return;
        }
        if(!Book.verifyISBN(isbn)){
            JOptionPane.showMessageDialog(null, "Invalid ISBN");
            return;
        }
        for(Book b : books){
            if(b.getISBN().equals(isbn)){
                JOptionPane.showMessageDialog(null, "A new copy of this book has been added");
                b.setCopies(b.getCopies()+1);
                return;
            }
        }
        AddBookScreen addBookScreen = new AddBookScreen(isbn);
        addBookScreen.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }

    private void removeBookButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String isbn = removeBookTextField.getText();
        if(isbn.equals("Enter an ISBN") || isbn.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter an ISBN");
            return;
        }
        if(!Book.verifyISBN(isbn)){
            JOptionPane.showMessageDialog(null, "Invalid ISBN");
            return;
        }
        for(Book b : books){
            if(b.getISBN().equals(isbn)){
                JOptionPane.showMessageDialog(null, "The book has been removed");
                if(b.getCopies() > 1){
                    b.setCopies(b.getCopies()-1);
                } else {
                    try {
                        Book.deleteBook(b);
                    } catch (Throwable throwable) {
                        throwable.printStackTrace();
                    }
                }
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Book not found");
    }

    private void updateBookButtonActionPerformed(java.awt.event.ActionEvent evt) {
          String isbn = updateBookTextField.getText();
        if(isbn.equals("Enter an ISBN") || isbn.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter an ISBN");
            return;
        }
        if(!Book.verifyISBN(isbn)){
            JOptionPane.showMessageDialog(null, "Invalid ISBN");
            return;
        }
        for(Book b : books){
            if(b.getISBN().equals(isbn)){
                UpdateBookScreen updateBookScreen = new UpdateBookScreen(b);
                updateBookScreen.setVisible(true);
                this.setVisible(false);
                this.dispose();
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Book not found");
    }

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        LoginScreen loginScreen = new LoginScreen();
        loginScreen.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private ArrayList<Book> books;
    private javax.swing.JButton addBookButton;
    private javax.swing.JLabel addBookLabel;
    private javax.swing.JTextField addBookTextField;
    private javax.swing.JButton generateReportButton;
    private javax.swing.JLabel generateReportLabel;
    private javax.swing.JTextField generateReportTextField;
    private javax.swing.JLabel librarianLabel;
    private javax.swing.JPanel librarianPanel;
    private javax.swing.JButton logoButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton removeBookButton;
    private javax.swing.JLabel removeBookLabel;
    private javax.swing.JTextField removeBookTextField;
    private javax.swing.JButton updateBookButton;
    private javax.swing.JLabel updateBookLabel;
    private javax.swing.JTextField updateBookTextField;
    // End of variables declaration
}
