
package Screens;

import BookClass.Book;
import BookClass.Genre;
import BookClass.Status;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *A
 * @author belal
 */
public class UpdateBookScreen extends JFrame {

    /**
     * Creates new form UpdateBookScreen
     */
    public UpdateBookScreen(Book book) {
        initComponents();this.book = book;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        JLabel updateBookHeader = new JLabel();
        JLabel genreLabel = new JLabel();
        JLabel titleLabel = new JLabel();
        JLabel descLabel = new JLabel();
        JComboBox<String> availabilityComboBox = new JComboBox<>();
        JLabel availabilityLabel = new JLabel();
        JLabel keywordLabel = new JLabel();
        JLabel authorLabel = new JLabel();
        JScrollPane keywordScrollPanel = new JScrollPane();
        JTextArea keywordTextArea = new JTextArea();
        JTextField bookTitleTextField = new JTextField();
        JTextField authorTextField = new JTextField();
        JComboBox<String> genreComboBox = new JComboBox<>();
        // Variables declaration - do not modify
        JButton confirmUpdateBookButton = new JButton();
        JScrollPane descScrollPanel = new JScrollPane();
        JTextArea descTextArea = new JTextArea();
        JLabel imagePathLabel = new JLabel();
        JTextField imagePathTextField = new JTextField();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        updateBookHeader.setFont(new Font("Segue UI", Font.BOLD, 18)); // NOI18N
        updateBookHeader.setText("Update Book");

        genreLabel.setFont(new Font("Segue UI", Font.PLAIN, 14)); // NOI18N
        genreLabel.setHorizontalAlignment(SwingConstants.CENTER);
        genreLabel.setText("Genre");

        titleLabel.setFont(new Font("Segue UI", Font.PLAIN, 14)); // NOI18N
        titleLabel.setHorizontalAlignment(SwingConstants.CENTER);
        titleLabel.setText("Title");

        descLabel.setFont(new Font("Segue UI", Font.PLAIN, 14)); // NOI18N
        descLabel.setHorizontalAlignment(SwingConstants.CENTER);
        descLabel.setText("Description");

        availabilityComboBox.setModel(new DefaultComboBoxModel<>(new String[] {"AVAILABLE", "UNAVAILABLE", "BORROWED", "LATE", "LOST", "DAMAGED"}));
        // AVAILABLE, UNAVAILABLE, BORROWED, LATE, LOST, DAMAGED
        availabilityLabel.setFont(new Font("Segue UI", Font.PLAIN, 14)); // NOI18N
        availabilityLabel.setHorizontalAlignment(SwingConstants.CENTER);
        availabilityLabel.setText("Availability");

        keywordLabel.setFont(new Font("Segue UI", Font.PLAIN, 14)); // NOI18N
        keywordLabel.setHorizontalAlignment(SwingConstants.CENTER);
        keywordLabel.setText("Keywords");

        authorLabel.setFont(new Font("Segue UI", Font.PLAIN, 14)); // NOI18N
        authorLabel.setHorizontalAlignment(SwingConstants.CENTER);
        authorLabel.setText("Authors");

        keywordTextArea.setColumns(20);
        keywordTextArea.setRows(5);
        keywordScrollPanel.setViewportView(keywordTextArea);

        genreComboBox.setModel(new DefaultComboBoxModel<>(new String[] { "NONE","HISTORY", "PHILOSOPHY"
                , "SCIENCE", "FICTION","MYSTERY","ROMANCE","HORROR","FANTASY","COOKING","ART","MUSIC","SPORTS","OTHER" }));

        confirmUpdateBookButton.setFont(new Font("Segue UI", Font.BOLD, 14)); // NOI18N
        confirmUpdateBookButton.setText("Confirm");
        confirmUpdateBookButton.addActionListener(this::ConfirmUpdateBookButtonActionPerformed);

        descTextArea.setColumns(20);
        descTextArea.setRows(5);
        descScrollPanel.setViewportView(descTextArea);

        imagePathLabel.setHorizontalAlignment(SwingConstants.CENTER);
        imagePathLabel.setText("Image Path");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(212, 212, 212)
                                                .addComponent(updateBookHeader))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(218, 218, 218)
                                                .addComponent(confirmUpdateBookButton, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(imagePathLabel, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(imagePathTextField, GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(descLabel, GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                                                        .addComponent(genreLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(titleLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(genreComboBox, GroupLayout.Alignment.LEADING, 0, 132, Short.MAX_VALUE)
                                                                        .addComponent(descScrollPanel, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                                        .addComponent(bookTitleTextField))))
                                                .addGap(40, 40, 40)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(authorLabel, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(authorTextField, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(keywordLabel, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(keywordScrollPanel, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(availabilityLabel, GroupLayout.PREFERRED_SIZE, 78, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(availabilityComboBox, GroupLayout.PREFERRED_SIZE, 138, GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(updateBookHeader)
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(titleLabel, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(bookTitleTextField, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(genreComboBox, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(genreLabel, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(descLabel, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(descScrollPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(authorLabel, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(authorTextField, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                                                .addGap(9, 9, 9)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(availabilityLabel, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(availabilityComboBox, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(keywordLabel, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(keywordScrollPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(imagePathLabel)
                                        .addComponent(imagePathTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addComponent(confirmUpdateBookButton, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>

    private void ConfirmUpdateBookButtonActionPerformed(ActionEvent evt) {
        // TODO add your handling code here:
        if(!bookTitleTextField.getText().isBlank())
        {
            book.setTitle(bookTitleTextField.getText());
        }
        if(!authorTextField.getText().isBlank())
        {
            book.setAuthor(authorTextField.getText());
        }



        Genre genre = null;

        try {
            for (Genre g : Genre.values()) {
                if (g.toString().equals(Objects.requireNonNull(genreComboBox.getSelectedItem()).toString()))
                    genre = g;
            }
            book.setGenreType(genre);
        }catch(NullPointerException npe){
            JOptionPane.showMessageDialog(null, "Something went wrong when selecting a genre", "Error", JOptionPane.ERROR_MESSAGE);
        }



        Status status = null;

        try{
            for(Status s: Status.values())
                if(s.toString().equals(availabilityComboBox.getSelectedItem().toString()))
                    status = s;
            book.setAvailability(status);
        }catch(NullPointerException npe){
            JOptionPane.showMessageDialog(null, "Something went wrong when selecting an availability status", "Error", JOptionPane.ERROR_MESSAGE);
        }


        if(!descTextArea.getText().isBlank())
            book.setDescription(descTextArea.getText());

        if(!imagePathTextField.getText().isBlank())
            book.setImagePath(imagePathTextField.getText());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            Logger.getLogger(UpdateBookScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> new UpdateBookScreen(new Book()).setVisible(true));
    }
    Book book;
    JLabel updateBookHeader = new JLabel();
    JLabel genreLabel = new JLabel();
    JLabel titleLabel = new JLabel();
    JLabel descLabel = new JLabel();
    JComboBox<String> availabilityComboBox = new JComboBox<>();
    JLabel availabilityLabel = new JLabel();
    JLabel keywordLabel = new JLabel();
    JLabel authorLabel = new JLabel();
    JScrollPane keywordScrollPanel = new JScrollPane();
    JTextArea keywordTextArea = new JTextArea();
    JTextField bookTitleTextField = new JTextField();
    JTextField authorTextField = new JTextField();
    JComboBox<String> genreComboBox = new JComboBox<>();
    // Variables declaration - do not modify
    JButton confirmUpdateBookButton = new JButton();
    JScrollPane descScrollPanel = new JScrollPane();
    JTextArea descTextArea = new JTextArea();
    JLabel imagePathLabel = new JLabel();
    JTextField imagePathTextField = new JTextField();
    // End of variables declaration
}
